### ISSUE TITLE
Any updates? It's almost a week.

### ISSUE THREAD

**Issue by Kenner-G** [notanewbie/LegalStream#15]

**Comment by notanewbie** [comment]
Hmm...not sure what you mean. I usually only add updates when necessary (a channel's URL changed, the channel shut down, I found a new channel, etc.). However, you could be referring to this project here: https://github.com/notanewbie/LegalStream/projects/1? I had to take a break from working on it because I'm really busy with the SAT and stuff right now, but plan to pick that back up next week.

**Comment by Kenner-G** [comment]
Okay cool.
