### ISSUE TITLE
GitHub Exudos - Should We Participate?

### ISSUE THREAD

**Issue by notanewbie** [notanewbie/LegalStream#22]
Hey guys, it's come to my attention that since Microsoft has acquired GitHub, loads of people have been fleeing GitHub and migrating to other hosting services. Should I do the same, and if so, where? Key requirements for a new hosting site would be 1) It's free and 2) Offers hosting that allows reading of raw files

**Comment by mikhoul** [comment]
You don't need to change unless something really change here (which I doubt), only fanatics or Microsoft haters have moved have moved to Gitlab.

Public repo will always be free and moreover Github will be managed independently than other Microsoft branches

I don't like Microsoft as company but there is no need at this moment to migrate all my repos on Gitlab, it will be just harder for everyone to find them since it's lot harder for the casual users to search on Gitlab than to search here on Github. :wink: 

Regards :octocat:

**Comment by notanewbie** [comment]
Thanks for the feedback, @mikhoul!

**Comment by notanewbie** [comment]
Not really. Seems like nobody's interested in migrating. Closing.
